input_data_path: "data/raw/heart.csv"
output_model_path: "models/model_trees.pkl"
metric_path: "models/metrics_trees.json"
splitting_params:
  val_size: 0.2
  random_state: 100
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  use_scaling_for_num_features: False
  # features_to_drop:
    # - ""
  target_col: "target"

