apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
spec:
  containers:
    - image: kpotoh/online_inference:v2
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "250Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /healz
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 5