apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-ml
  template:
    metadata:
      name: fastapi-ml
      labels: 
        app: fastapi-ml
    spec:
      containers:
        - image: kpotoh/online_inference:v2
          name: fastapi-ml
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
