apiVersion: v1
kind: Pod
metadata:
  name: online-inference-res
spec:
  containers:
    - image: kpotoh/online_inference:v1
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "250Mi"
          cpu: "500m"
        limits:
          memory: "500Mi"
          cpu: "500m"
